### ISSUE TITLE
No module named 'serial'

### ISSUE THREAD

**Issue by egomes951** [Dentrax/MMM-ArduPort#2]
Hi,
I've installed this module following every step. If I run the Python script arduport it seems everything is ok
pi@raspberrypi:~/MagicMirror/modules/MMM-ArduPort/arduport $ python arduport.py
{"debug": "SerialPort shell started..."}
{"debug": "Waiting Ardunio to connect on port..."}
{"status": {"data": "connected", "name": "connect"}}
{"sensor": {"data": "0", "name": "TEMP01"}}
{"sensor": {"data": "1", "name": "TEMP01"}}

But when I start my Magic Mirror I get this :

Whoops! There was an uncaught exception...
{ Error: ImportError: No module named 'serial'
    at PythonShell.parseError (/home/pi/MagicMirror/modules/MMM-ArduPort/node_modules/python-shell/index.js:246:21)
    at terminateIfNeeded (/home/pi/MagicMirror/modules/MMM-ArduPort/node_modules/python-shell/index.js:129:32)
    at ChildProcess.<anonymous> (/home/pi/MagicMirror/modules/MMM-ArduPort/node_modules/python-shell/index.js:121:13)
    at ChildProcess.emit (events.js:197:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    ----- Python Traceback -----
    File "modules/MMM-ArduPort/arduport/arduport.py", line 19, in <module>
      import serial
  traceback:
   `Traceback (most recent call last):\n  File "modules/MMM-ArduPort/arduport/arduport.py", line 19, in <module>\n    import serial\nImportError: No module named 'serial'\n`,
  executable: 'python3',
  options: null,
  script: 'modules/MMM-ArduPort/arduport/arduport.py',
  args:
   [ '{"portname":"/dev/ttyUSB0","updateInterval":1,"animationSpeed":1000,"displayIcons":true,"iconSize":"small","labelSize":"medium","showDescription":true,"useColors":true,"sensor":{"description":null,"maxValue":null,"maxFormat":null,"highestValue":null,"highestFormat":null,"highValue":null,"highFormat":null,"lowValue":null,"lowFormat":null,"lowestValue":null,"lowestFormat":null,"minValue":null,"minFormat":null,"error":null},"developerMode":false,"hideLoading":false,"hideWaiting":false,"sensors":[{"name":"TEMP01","description":"Temperatura S1","maxValue":50,"maxFormat":"({0} ppm) MAXIMUM","highestValue":30,"highestFormat":"({0} ppm) CRITICAL","highValue":15,"highFormat":"({0} ppm) EMERGENCY","lowValue":10,"lowFormat":"({0} ppm) LOW","lowestValue":5,"lowestFormat":"({0} ppm) VERY LOW","minValue":0,"minFormat":"({0} ppm) OK"}]}' ],
  exitCode: 1 }

Can you please help ?

Thanks,
Elisio

**Comment by egomes951** [comment]
OK. I fix this problem with sudo apt-get install python3-serial....

Thanks anyway

**Comment by kiurow590** [comment]
hi, i've a problem with the module. the module captures the sensors that I use, but it can't return a value. and when I execute the arduport.py. it returns an error "No module named 'serial'". Can you help me to find a solution, or can you give me another solution? thanks for your answer.

**Comment by Dentrax** [comment]
@egomes951 @kiurow590 

Sorry to hear that. I updated [required dependencies](https://github.com/Dentrax/MMM-ArduPort/blob/master/README.md#dependencies) to run the project.
